# Generated by Django 5.0.6 on 2026-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B1', max_length=2),
        ),
    ]
