# Generated by Django 5.0.6 on 2026-09-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification_user_first_name_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
