# Generated by Django 5.0.6 on 2026-06-12 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200, unique=True)),
                ('turkish', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, default='', max_length=10)),
                ('part_of_speech', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kelime',
                'verbose_name_plural': 'Kelimeler',
                'ordering': ['english'],
            },
        ),
        migrations.CreateModel(
            name='WordImageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_urls', models.JSONField(default=list)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_cache', to='words.word')),
            ],
            options={
                'verbose_name': 'Görsel Önbellek',
                'verbose_name_plural': 'Görsel Önbellekler',
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('seen_count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='words.word')),
            ],
            options={
                'verbose_name': 'Kullanıcı Kelimesi',
                'verbose_name_plural': 'Kullanıcı Kelimeleri',
                'ordering': ['score'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
