# Generated by Django 5.0.6 on 2026-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='turkish',
            field=models.JSONField(default=list),
        ),
    ]
